### ISSUE TITLE
Nondescriptive error message for NATS connection

### ISSUE THREAD

**Issue by brooksmtownsend** [wascc/gantry#24]
Upon running the `wascc-host` binary version `0.13.0` for linux without NATS running, the following message shows:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }',
/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gantryclient-0.0.9/src/lib.rs:107:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I believe it's caused by the unwrap here:
https://github.com/wascc/gantry/blob/master/client/gantryclient/src/lib.rs#L107

I think we should try and catch the NATS connection unwraps and hint that the user needs to be running NATS as a prerequisite, especially with wascc-host shipping with the lattice capability as a default

**Comment by autodidaddict** [comment]
This is odd. The gantry client shouldn't be invoked at all if it hasn't been registered with the host. Gantry support should be enabled but you actually need to add a Gantry client to the host builder before it will attempt to connect.

Are you adding a gantry client to the host?

**Comment by brooksmtownsend** [comment]
I am not, I'm not using a manifest either, just running `wascc-host` 
```
➜  wascc-host --version
wascc-host 0.13.0
➜  wascc-host
[2020-09-27T11:59:32Z INFO ] Gantry client created.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message
: "Connection refused" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gantryclient-0.0.9/src/lib.rs:10
7:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I don't have a specific use case for creating a blank host, I just wanted to see it run. Downloaded the linux binary on WSL2

**Comment by autodidaddict** [comment]
Okay so this is likely a bug with both the Wascc host (creating an unwanted gantry client) and the gantry client for doing an unwrap instead of bubbling the error back up.

**Comment by brooksmtownsend** [comment]
Thoughts of closing this in favor of #91?

**Comment by autodidaddict** [comment]
Yeah we need to refactor that get connection to return a result and not unwrap
